name: Build Zip Test

on:
  push:
    branches:
      - master

jobs:
  zip-n-push:
    name: Zip and Push
    runs-on: ubuntu-latest
    steps:
      - name: Zip Folder
        run: |
          cd ../ # I added this
          rm -rf GitHubActionsTest.zip
          zip -r GitHubActionsTest.zip GitHubActionsTest -x ".git/*" ".github/*"